# MBS R Challenge #1, Feb. 11, 2013
#
# Directions:
#
# 1. Save this file to your computer as LastnameFirstname_R1.r 
#    replacing Lastname and Firstname with your name. The "R1" stands 
#    for this R1 challenge.
# 2. Type your name here:   Daniel Payne
# 3. Add your solutions below the questions.
# 4. Do not delete any of the instructions we have provided.
# 5. When done please email this file to hartvig@geneseo.edu and 
#    leary@geneseo.edu. Put MBS in the subject line.
# 6. No fooling around with the grading variable "GGG".

GGG = 10     # Please leave this alone - it's for grading purposes.

##############################################################
# Question #1: (2 pts)
#
# Sum the first 1000 values from the uniform random
# number sequence generated by the runif() function if you set
# the random number seed to 100.

set.seed(100) # You should leave this in place

nums=runif(1000)
sum=0
for(i in 1:100){
	sum=nums[i]+sum
	
}
print(sum)

##############################################################
# Question #2: (3 pts)

# Use a for loop to create a list of 10 numbers from the 
# uniform random number sequence. The numbers should be
# added to the array L one at a time using runif(1), which
# returns just one number. Make a very simple barplot
# of these data using the code provided. Don't worry about
# making this graph look better. Notice that I've broken
# the problem up into an algorithm with logical steps to
# complete.

# set the random
set.seed(100)

# set up the array to hold the answer
L = numeric(10) # creates an array of 10 zeroes.

# create the loop that correctly fills up L
for(i in 1:10){
	L=append(L,runif(1))
}

# graph the result
barplot(L)




##############################################################
# QUESTION 3: (5 pts)
#
# Let's assume that a bacterium can move only left or right along
# a straight line (one dimensional movement). It goes left (-1) or
# right (+1) randomly (no standing still!). Each bacterium starts
# at 0 and moves 24 times. Graph the distribution of 1000 bacteria 
# that independently move in this fashion (you will have more
# than one bacterium that stops in the same place).
#
# Some guidelines:
# a. use the function call set.seed(100) check
# b. Collect the 1000 values of the locations of each of 
#    the 1000 bacteria after 24 time steps in the array L.
#    Notice that the location of each bacterium (L) is 0 
#    at time 1. Check
# c. You can easily count the number of bacteria that ended
#    up at different locations using the table() function.
#    If you have a list of 1000 values in an array called L
#    then the table command will do this:

# > table(L)
# L
# -5  -3  -1   1   3   5 
# 34 155 288 314 171  38 

# d. Make a lovely barplot of the locations using
#    the following:

# barplot(table(L))



# Just in case you're freaking out let's think about a
# very rough algorithm for this. You might want to elaborate
# on it before writing code:
#
# 1. You need a loop for the 1000 individual bacteria.
# 2. You need another loop inside the above loop for the 24
#    steps that each bacterium takes.
# 3. You need to somehow record the location of where each
#    bacterium stopped
#----------------------------------------------------
# Place your original code below (snagged from the internet
# will result in earning zero points). A correct solution 
# will, when run, produce a lovely barplot.

set.seed(100) # run each time to get correct answer
L=c()
for(ii in 1:1000){#Runs through each Bacteria
	move=0
	for(i in 1:24){#Each bacteria's movement
		mind=runif(1,min=0,max=1)#The default is 0 to 1 anyways so the min max kwargs aren't needed
		if(mind>.5){
			move=move+1			
		}
		else{
			move=move-1
		}
	}
	L=append(L,move)	
}
table(L)
#x11()
barplot(table(L))

######################################################

cat("You earned ",GGG,"points\n")

